# Generated by Django 4.1.3 on 2022-12-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Strain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("indica", "Indica"),
                            ("sativa", "Sativa"),
                            ("hybrid", "Hybrid"),
                            ("indica_hybrid", "Indica Hybrid"),
                            ("sativa_hybrid", "Sativa Hybrid"),
                        ],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                (
                    "effect",
                    models.CharField(
                        choices=[
                            ("aroused", "Aroused"),
                            ("creative", "Creative"),
                            ("energetic", "Energetic"),
                            ("euphoric", "Euphoric"),
                            ("focused", "Focused"),
                            ("giggly", "Giggly"),
                            ("happy", "Happy"),
                            ("hungry", "Hungry"),
                            ("relaxed", "Relaxed"),
                            ("sleepy", "Sleepy"),
                            ("talkative", "Talkative"),
                            ("tingly", "Tingly"),
                            ("uplifted", "Uplifted"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("thc", models.IntegerField()),
                (
                    "aroma",
                    models.CharField(
                        choices=[
                            ("ammonia", "Ammonia"),
                            ("apple", "Apple"),
                            ("apricot", "Apricot"),
                            ("berry", "Berry"),
                            ("blueberry", "Blueberry"),
                            ("blue_cheese", "Blue Cheese"),
                            ("butter", "Butter"),
                            ("cheese", "Cheese"),
                            ("chemical", "Chemical"),
                            ("chestnut", "Chestnut"),
                            ("citrus", "Citrus"),
                            ("coffee", "Coffee"),
                            ("diesel", "Diesel"),
                            ("earthy", "Earthy"),
                            ("flowery", "Flowery"),
                            ("grape", "Grape"),
                            ("grapefruit", "Grapefruit"),
                            ("honey", "Honey"),
                            ("lavender", "Lavender"),
                            ("lemon", "Lemon"),
                            ("lime", "Lime"),
                            ("mango", "Mango"),
                            ("menthol", "Menthol"),
                            ("mint", "Mint"),
                            ("nutty", "Nutty"),
                            ("orange", "Orange"),
                            ("peach", "Peach"),
                            ("pear", "Pear"),
                            ("pepper", "Pepper"),
                            ("pine", "Pine"),
                            ("pineapple", "Pineapple"),
                            ("plum", "Plum"),
                            ("pungent", "Pungent"),
                            ("rose", "Rose"),
                            ("sage", "Sage"),
                            ("skunk", "Skunk"),
                            ("spicy_herbal", "Spicy/Herbal"),
                            ("strawberry", "Strawberry"),
                            ("sweet", "Sweet"),
                            ("tar", "Tar"),
                            ("tea", "Tea"),
                            ("tobacco", "Tobacco"),
                            ("tree_fruit", "Tree fruit"),
                            ("tropical", "Tropical"),
                            ("vanilla", "Vanilla"),
                            ("violet", "Violet"),
                            ("woody", "Woody"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("grow_info", models.TextField()),
                ("image", models.FilePathField(path="/img")),
            ],
        ),
    ]
