# Generated by Django 4.1.3 on 2022-12-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="image",
            field=models.FilePathField(path="strains/img"),
        ),
    ]
