# Generated by Django 4.1.3 on 2022-12-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0002_alter_strain_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
