# Generated by Django 4.1.3 on 2022-12-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0015_alter_strain_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="image",
            field=models.ImageField(upload_to="strains/img"),
        ),
    ]
