# Generated by Django 4.1.3 on 2022-12-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0018_alter_strain_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="image",
            field=models.ImageField(upload_to="media/img"),
        ),
    ]
