# Generated by Django 4.1.3 on 2022-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0023_alter_strain_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="thc",
            field=models.IntegerField(),
        ),
    ]
