# Generated by Django 4.1.3 on 2022-12-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0024_alter_strain_thc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="image",
            field=models.ImageField(upload_to="strains/img"),
        ),
    ]
