# Generated by Django 4.1.3 on 2022-12-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0025_alter_strain_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="breeder",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="strain",
            name="lineage",
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
