# Generated by Django 4.1.3 on 2022-12-06 02:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0027_alter_strain_aroma_alter_strain_breeder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="aroma",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("ammonia", "Ammonia"),
                    ("apple", "Apple"),
                    ("apricot", "Apricot"),
                    ("berry", "Berry"),
                    ("blueberry", "Blueberry"),
                    ("blue_cheese", "Blue Cheese"),
                    ("butter", "Butter"),
                    ("cheese", "Cheese"),
                    ("chemical", "Chemical"),
                    ("chestnut", "Chestnut"),
                    ("citrus", "Citrus"),
                    ("coffee", "Coffee"),
                    ("diesel", "Diesel"),
                    ("earthy", "Earthy"),
                    ("flowery", "Flowery"),
                    ("grape", "Grape"),
                    ("grapefruit", "Grapefruit"),
                    ("honey", "Honey"),
                    ("lavender", "Lavender"),
                    ("lemon", "Lemon"),
                    ("lime", "Lime"),
                    ("mango", "Mango"),
                    ("menthol", "Menthol"),
                    ("mint", "Mint"),
                    ("nutty", "Nutty"),
                    ("orange", "Orange"),
                    ("peach", "Peach"),
                    ("pear", "Pear"),
                    ("pepper", "Pepper"),
                    ("pine", "Pine"),
                    ("pineapple", "Pineapple"),
                    ("plum", "Plum"),
                    ("pungent", "Pungent"),
                    ("rose", "Rose"),
                    ("sage", "Sage"),
                    ("skunk", "Skunk"),
                    ("spicy_herbal", "Spicy/Herbal"),
                    ("strawberry", "Strawberry"),
                    ("sweet", "Sweet"),
                    ("tar", "Tar"),
                    ("tea", "Tea"),
                    ("tobacco", "Tobacco"),
                    ("tree_fruit", "Tree fruit"),
                    ("tropical", "Tropical"),
                    ("vanilla", "Vanilla"),
                    ("violet", "Violet"),
                    ("woody", "Woody"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="strain",
            name="effect",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("aroused", "Aroused"),
                    ("creative", "Creative"),
                    ("energetic", "Energetic"),
                    ("euphoric", "Euphoric"),
                    ("focused", "Focused"),
                    ("giggly", "Giggly"),
                    ("happy", "Happy"),
                    ("hungry", "Hungry"),
                    ("relaxed", "Relaxed"),
                    ("sleepy", "Sleepy"),
                    ("talkative", "Talkative"),
                    ("tingly", "Tingly"),
                    ("uplifted", "Uplifted"),
                ],
                max_length=50,
            ),
        ),
    ]
