# Generated by Django 4.1.3 on 2022-12-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0029_alter_strain_aroma"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="stock",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("limited_stock", "Limited stock"),
                    ("out_of_stock", "Out of stock"),
                    ("gone_forever", "Gone forever"),
                ],
                default="gone_forever",
                max_length=20,
            ),
        ),
    ]
