# Generated by Django 4.1.3 on 2022-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0030_strain_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="lineage",
            field=models.CharField(max_length=75, null=True),
        ),
    ]
