# Generated by Django 4.1.3 on 2022-12-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strains", "0031_alter_strain_lineage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strain",
            name="stock",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("limited_stock", "Limited stock"),
                    ("out_of_stock", "Out of stock"),
                    ("gone_forever", "Gone forever"),
                    ("coming_soon", "Coming soon"),
                ],
                default="gone_forever",
                max_length=20,
            ),
        ),
    ]
